version: '3'

services:
   web:
     build: .
     environment:
       RABBITMQ_BROKER_URL: rabbitmq
     depends_on:
       - rabbitmq
     ports:
       - "8080:8080"

   rabbitmq:
     image: rabbitmq:3-management
     ports:
       - "5672:5672"
       - "15672:15672"

