server:
  address: 0.0.0.0
  port: 8080
rabbitmq:
  brokerUrl: ${RABBITMQ_BROKER_URL:localhost}
queue:
  name: ${QUEUE_NAME:itemsToProcessQueue}
worker:
  name: ${HOSTNAME:worker1}
  enabled: ${WORKER_ENABLED:false}
store:
  enabled: ${STORE_ENABLED:true}

spring.rabbitmq.listener.simple.prefetch: 1
